version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t $DOCKERHUB_USERNAME/vrms-server:$CIRCLE_BRANCH .
      - run: docker push $DOCKERHUB_USERNAME/vrms-server:$CIRCLE_BRANCH
  deploy:
    machine: true
    steps:
      - run: ssh $SSH_USER@$SSH_HOST "docker rm -f vrms-server"
      - run: ssh $SSH_USER@$SSH_HOST "docker pull $DOCKERHUB_USERNAME/vrms-server:$CIRCLE_BRANCH"
      - run: ssh $SSH_USER@$SSH_HOST "docker run --name vrms-server -d -p 8080:8080 $DOCKERHUB_USERNAME/vrms-server:$CIRCLE_BRANCH"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master