version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t $DOCKERHUB_USERNAME/vrms-server:latest .
      - run: docker push $DOCKERHUB_USERNAME/vrms-server:latest