version: 2

jobs:
  build:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /home/app
    steps:
      - checkout
      - run: docker build -t $DOCKERHUB_USERNAME/vrms-server:latest .
      - run: docker push $DOCKERHUB_USERNAME/vrms-server:latest